### ISSUE TITLE
Thanks for your interest

### ISSUE THREAD

**Issue by sh-lee-prml** [CODEJIN/HierSpeech#1]
Hi I'm Sang-Hoon Lee. I came across your project page 

Thanks for your interest in our paper, HierSpeech

I found out some different points with our implementation.

### 1. Discriminator
- Following VITS, we use the MSD (only the first scale of it) with MPD.
- In addition, we recommend replacing the MSD with MS-STFTD of EnCodec. This will improve the audio quality. (MPD + MS-STFTD)

### 2. External aligner
- When using an external aligner (not using MAS), I recommend using the additional frame prior network used in VISinger or Period VITS. Although using guassian upsampler may reduce the mismatch problem between two distributions, the frame-level prior network simply solve it. 

### 3. SSL Model
- In our case, the representation of XLS-R is better than that of WavLM, specifically in other languages. 

Thanks again 
😊

**Comment by CODEJIN** [comment]
Hi, Sang-hoon.

Thanks for the great paper and the advices. It's been a lot of studying. I will apply what you said soon!

Heejo

**Comment by hdmjdp** [comment]
@sh-lee-prml Expect your offical code!

**Comment by CODEJIN** [comment]
Hello, Sang-hoon.

Your advice has been applied to this repository, except for #2. The reason for excluding #2 is that the repository now uses MAS. If you have any further opinions in the future, please let me know. Thank you once again for your advice!

Heejo
