### ISSUE TITLE
Have you got a good result?

### ISSUE THREAD

**Issue by hdmjdp** [CODEJIN/HierSpeech#2]

**Comment by CODEJIN** [comment]
Hi, hdmjdp.

I am currently testing, but I have determined that some improvements are needed. In particular, it appears that the modified discriminator in the existing model is not functioning as intended, and I am working on improving it.

Thanks,

Heejo.

**Comment by CODEJIN** [comment]
Hello, hdmjdp.

After fixing some bugs and improving the code, I have confirmed that the training is proceeding normally. However, as this implementation project is being conducted as a personal study, the model could not be trained on the same equipment and for the same duration as mentioned in the original paper. Therefore, I cannot confidently say that the model can be trained to the same level as described in the paper. I kindly ask for your understanding regarding this limitation.
If you have any suggestions for improving the code, please let me know.

Best regards,

Heejo
